name: aoc-haskell
version: 0.8.0.0
github: "Vest/aoc-haskell"
license: BSD3
author: "Vest"
maintainer: "Vest@users.noreply.github.com"
copyright: "2021 Vest"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/Vest/aoc-haskell#readme>

library:
  source-dirs: src/
  exposed-modules:
    - Advent
    - Day1
    - Day2
    - Day3
    - Day4
    - Day5
    - Day6
    - Day7
    - Day8
    - DayX
  dependencies:
    - base >= 4.7 && < 5
    - split
    - http-client
    - http-conduit
    - bytestring
    - utf8-string
    - containers
    - sort
    - pureMD5

executables:
  aoc-haskell:
    main: Main.hs
    source-dirs:
      - app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
      - aoc-haskell

tests:
  aoc-haskell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
      - HUnit
      - aoc-haskell
      - containers
